version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - .:/var/www/byson
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: byson
      MYSQL_USER: django
      MYSQL_PASSWORD: django
  web:
    build: .
    command: sh -c "./wait-for-it.sh db:3306; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/www/byson
    ports:
      - "8080:8000"
    depends_on:
      - db
