# Generated by Django 2.2.1 on 2019-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toggls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='gap_ratio',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tid',
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_dur',
            field=models.IntegerField(),
        ),
    ]
