# Generated by Django 2.2.1 on 2019-05-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toggls', '0003_auto_20190509_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(unique=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_dur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toggls.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(unique=True, verbose_name='date started'),
        ),
    ]
