# Generated by Django 2.2.1 on 2019-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toggls', '0005_auto_20190510_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(verbose_name='date started'),
        ),
    ]
